[package]
name = "crane-arena"
version = "0.0.0"
edition = "2021"

[dependencies]
boxcar = "0.1.0"
crossbeam-queue = "0.3.8"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "benches"
harness = false


